pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-a.gz -param output=cleanedOutput/a cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-b.gz -param output=cleanedOutput/b cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-c.gz -param output=cleanedOutput/c cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-d.gz -param output=cleanedOutput/d cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-e.gz -param output=cleanedOutput/e cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-f.gz -param output=cleanedOutput/f cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-g.gz -param output=cleanedOutput/g cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-h.gz -param output=cleanedOutput/h cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-i.gz -param output=cleanedOutput/i cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-j.gz -param output=cleanedOutput/j cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-k.gz -param output=cleanedOutput/k cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-l.gz -param output=cleanedOutput/l cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-m.gz -param output=cleanedOutput/m cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-n.gz -param output=cleanedOutput/n cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-o.gz -param output=cleanedOutput/o cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-p.gz -param output=cleanedOutput/p cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-q.gz -param output=cleanedOutput/q cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-r.gz -param output=cleanedOutput/r cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-s.gz -param output=cleanedOutput/s cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-t.gz -param output=cleanedOutput/t cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-u.gz -param output=cleanedOutput/u cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-v.gz -param output=cleanedOutput/v cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-w.gz -param output=cleanedOutput/w cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-x.gz -param output=cleanedOutput/x cleaner.pig
pig -param input=ngrams/1grams/googlebooks-eng-all-1gram-20120701-y.gz -param output=cleanedOutput/y cleaner.pig
